### ISSUE TITLE
Unhandled exception. YoutubeExplode.Exceptions.TransientFailureException: Video watch page is broken.

### ISSUE THREAD

**Issue by Giraffaman** [L0um15/SpotiSharp#10] opened 2021-03-31 22:06 UTC
**Describe the bug**
Getting the following exception:
```
Connecting To Spotify...
Making requests to Spotify...
Downloading ::::: Moderat - Intruder
Unhandled exception. YoutubeExplode.Exceptions.TransientFailureException: Video watch page is broken.
In most cases, this error indicates that the problem is on YouTube's side and this is not a bug in the library.
To resolve this error, please wait some time and try again.
If this issue persists, please report it on the project's GitHub page.
   at YoutubeExplode.ReverseEngineering.Responses.WatchPage.<>c__DisplayClass11_0.<<GetAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at YoutubeExplode.Internal.Retry.WrapAsync[T](Func`1 executeAsync)
   at YoutubeExplode.Internal.Retry.WrapAsync[T](Func`1 executeAsync)
   at YoutubeExplode.ReverseEngineering.Responses.WatchPage.GetAsync(YoutubeHttpClient httpClient, String videoId)
   at YoutubeExplode.Videos.Streams.StreamClient.GetStreamContextFromWatchPageAsync(VideoId videoId)
   at YoutubeExplode.Videos.Streams.StreamClient.GetManifestAsync(VideoId videoId)
   at SpotiSharp.DownloadHelpers.DownloadAndConvertTrack(YoutubeClient youtube, TrackInfo trackInfo) in D:\Projects\C#\SpotiSharp\DownloadHelpers.cs:line 14
   at SpotiSharp.Program.Main(String[] args) in D:\Projects\C#\SpotiSharp\Program.cs:line 127
```
**How To Reproduce**
Getting the above exception when attempting to download either a single track or entire playlist - song URL from above sample: https://open.spotify.com/track/6dS7rWtP9G7R1o2FSeomQe?si=f7a54af057ef4d4c

Reproduced in PowerShell v5.1, both with the self-contained version of SpotiSharp and with framework-dependent version with .Net 3.1.13 Runtime installed.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64
- OS Version: v20H2 (10.0.19042)

**Comment by L0um15** [comment] 2021-03-31 22:20
Working on it

**Comment by L0um15** [comment] 2021-03-31 22:46
After further investigation i found out that this issue occures on every track i tried so far. This was caused by changes in youtube api. This will be fixed over time. But for now i can't provide fix until library gets a update.

**Comment by L0um15** [comment] 2021-04-01 13:36
Good news, issue was solved and changes were commited to library. Once fix will reach the stable release at the end of the week i will update Spotisharp libraries. You can read more about it here: https://github.com/Tyrrrz/YoutubeExplode/issues/521

**Comment by Giraffaman** [comment] 2021-04-01 15:20
ah just read the linked issue - cool so we'll just wait and see here. Thanks for looking into this

**Comment by L0um15** [comment] 2021-04-07 08:54
Since Youtube-Explode didn't released stable update yet, as temporary fix i added `CONSENT` Cookie until update will be released.
Everything should work fine for now. Feel free to re-open this issue if problem persists

**Closed by L0um15** 2021-04-07 08:54 UTC
Labels: 🌗Caused by YouTube, 🐞bug, 👌good first issue
