### ISSUE TITLE
Downloaded song is wrong but metadata is right.

### ISSUE THREAD

**Issue by djcenk** [L0um15/SpotiSharp#41] opened 2023-11-10 18:22 UTC
**Describe the bug**

Recently I have been getting wrong results with spotisharp or manually downloading songs from youtube
The title of the song is correct but the content is wrong.

**How To Reproduce**
Include song/playlist you was looking for.
E.g. [https://open.spotify.com/track/28HX0PibeXSL6cfAsvwSgD]

https://open.spotify.com/playlist/37i9dQZF1DXa41CMuUARjl
Song name : Shermanology - Motown Philly
Downloaded song : meyra - gözlerinde kim var

**Screenshots**
Add screenshots to help explain your problem.

**Include latest log file**
Log file can be found inside app directory. It should be named like: log-{Year}{Month}{Day}{Hour}{Minute}{Second}.txt

**Desktop (please complete the following information):**
 - OS: [e.g. Linux, Windows] : windows
 - Kernel [e.g. 4.15.0-39-generic] (Linux only)
 - OS Version [e.g. 1809 build 17763.1577] (Windows only)

**Comment by L0um15** [comment] 2023-11-13 21:48
Duplicate of #36 

This track was released 3 days ago and now it gained some recognition. Spotisharp should be able to fetch it now.
Ps: im not talking about a original track that was released by Boyz II Men 7 years ago :)

**Comment by L0um15** [comment] 2023-11-13 21:50
Update: Now it is downloading as it should. Take a notice on the release date. New songs need to gain some recognition.

**Closed as completed by L0um15** 2023-11-13 21:50 UTC
Labels: 🌗Caused by YouTube
